version: '3'

services:
  paper:
    image: ghcr.io/timebertt/markdown-paper-setup/python:sha-26f1955
    command:
    - -c
    - "while true; do sleep 2; done"
    stdin_open: true
    tty: true
    cpu_count: 8
    volumes:
    - ".:/data"
