version: '3'

services:
  paper:
    image: ghcr.io/timebertt/markdown-paper-setup/python:sha-6d13db6
    command:
    - -c
    - "while true; do sleep 2; done"
    stdin_open: true
    tty: true
    volumes:
    - ".:/data"
