version: '3'

services:
  paper:
    # temporarily use manually built arm64 image
    image: ghcr.io/timebertt/markdown-paper-setup/python:arm64
    command:
    - -c
    - "while true; do sleep 2; done"
    stdin_open: true
    tty: true
    cpu_count: 8
    volumes:
    - ".:/data"
